on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: codehbchallengeapi
  AZURE_WEBAPP_PACKAGE_PATH: './codehbchallenge-api-webapp'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Debug -o codehbchallenge-api-webapp
    
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/appsettings.Development.json'
      env:
        ConnectionStrings.PostgreSQL: ${{ secrets.POSTGRESQL_CONNECTIONSTRING }}

    - name: Deploy using publish profile credentials
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
